### PR TITLE
Update site.mk, Raspi packages

### PR DESCRIPTION
**Pull request by Brother-Lal**
Added more USB networking modules
Added Raspberry PI A/B/B+/2 targets

Compiling for raspi still requires a BROKEN=1 flag, and the manual target

### CODE REVIEW

**Comment by rotanid** [comment]
thanks. are these additional kernel modules really only used in usb devices? their names don't sound like that and therefore the name USB_PACKAGES_NET_ADD is misleading.
have you tested both GLUON_TARGETs on the devices? if yes, you could also update https://github.com/tecff/gluon/blob/master/targets/targets.mk to remove the BROKEN switch for those you have tested.

**Comment by Brother-Lal** [comment]
All packages are usb wireless drivers or their dependencies:
https://wiki.openwrt.org/doc/howto/wireless.overview
https://wireless.wiki.kernel.org/en/users/drivers

kmod-ath9k-htc + kmod-ath9k-common + kmod-ath:
Atheros USB AR9271 and AR7010 family of chipsets. 

 kmod-rtl8192cu + kmod-rtl8187:
Realtek RTL8188CUS , etc - cheap edimax usbsticks

kmod-rt73-usb + kmod-carl9170 + kmod-brcmfmac:
Additional ones i found available

Just wanted to add a bunch more(even more or less unadequate ones) as space is not an issue on the Raspis. Better to include them, than to recompile and search for hours for the driver if its not in the default package.

I have tested only on Raspi B/B+ until now.
I will do a compile and deploy for Raspi 2.

Regarding the broken flag, i would still say all is experimental with the Raspis.
Out-of-the-box there is no wireless support, all has to be configured manually.

Either let them stay in the experimental repo or add a clear warning that some more manual labor is needed if deploying those.

Should i add the additional drivers to the x86/VM images as well?

**Comment by Brother-Lal** [comment]
Updated pull-request:
fixed a typo, line 179 should read brcm2708-bcm2709 instead of brcm2709-bcm2709

**Comment by Brother-Lal** [comment]
I have done a compile and install for both targets, everything seems to work fine, excluding the wireless configuration.
Done manually wifi works, both meshing and client.

**Comment by rotanid** [comment]
great, and i guess yes, we should&could add those additional modules to the x86 targets, too

edit:
perhaps we should document somewhere, what manual steps are remaining after flashing?

**Comment by Brother-Lal** [comment]
I added the drivers to the x86 targets.

regarding documentation - as soon as i have wiki access, i will add a section for network setup/useful commands

ps: i moved the raspi targets to non-broken in this commit: https://github.com/tecff/gluon/pull/1

**Pull request merged**
